### PR TITLE
AutoStake gentx

### PR DESCRIPTION
**Pull request by AutoStake-com**

### CODE REVIEW

**Comment by VT-Cosmos** [comment]
Hi @AutoStake-com 

Thank you for the submission. 
Some points including Region/Country + Discord handle are missing from the submission. Please note that there were some updates in the requirements. README . 
We would appreciate if you could check that all points are covered before the deadline of Feb 24th 1am.

**Comment by AutoStake-com** [comment]
Added Countries and Discord handles!

**Comment by VT-Cosmos** [comment]
@AutoStake-com 

We are moving the validator communication to a private group in the GovGen/AtomOne Discord. Which you can find here: https://discord.gg/atomone
Please join using the handle provided in your validator PR, or edit your user profile so that it designates your validator so that we can easily change your role

**Comment by giunatale** [comment]
Please update your gentx to follow the recommended values. please submit a gentx using the command as specified in https://github.com/atomone-hub/validator/tree/main/govgen-1#register-in-the-genesis

Your commision values must all be set to 0.

Please do this ASAP or you might be excluded from genesis

**Comment by giunatale** [comment]
Sorry guys but due to time constraints we weren't able to include you in the gentxs, even if we decided to accept your application.

We sill credited 25$GOVGEN to `govgen1j3y3ztv06y7w253jjpfj8uyq6cnyhnh2zpxeep` (the account you used in the gentx here) so you will be able to join the validator set post-genesis.
Should you decide to do so, please still follow the guidelines at https://github.com/atomone-hub/validator/tree/main/govgen-1#register-in-the-genesis for your validator

**Comment by AutoStake-com** [comment]
No problem, will join post-genesis

**Comment by AutoStake-com** [comment]
> Sorry guys but due to time constraints we weren't able to include you in the gentxs, even if we decided to accept your application.
> 
> We sill credited 25$GOVGEN to `govgen1j3y3ztv06y7w253jjpfj8uyq6cnyhnh2zpxeep` (the account you used in the gentx here) so you will be able to join the validator set post-genesis. Should you decide to do so, please still follow the guidelines at https://github.com/atomone-hub/validator/tree/main/govgen-1#register-in-the-genesis for your validator

We have joined post-genesis
https://test.explorer.ist/govgen/staking/govgenvaloper1j3y3ztv06y7w253jjpfj8uyq6cnyhnh2nr0cnm

**Pull request merged**
