### PR TITLE
Add Kayrosstack

### PR DESCRIPTION
**Pull request by MadoxLP**

### CODE REVIEW

**Comment by MadoxLP** [comment]
[gentx.json](https://github.com/atomone-hub/validator/files/14392223/gentx.json)

**Review by MadoxLP — COMMENTED** [review]
Work with @Okmadi

**Comment by Okmadi** [comment]
> _ No description provided. _

Good Work 🦾

**Comment by Okmadi** [comment]
[gentx.json](https://github.com/atomone-hub/validator/files/14392232/gentx.json)

**Comment by Okmadi** [comment]
I updated gentx and added more details about Kayrosstack

**Comment by VT-Cosmos** [comment]
@MadoxLP @Okmadi 

We are moving the validator communication to a private group in the GovGen/AtomOne Discord. Which you can find here: https://discord.gg/atomone
Please join using the handle provided in your validator PR, or edit your user profile so that it designates your validator so that we can easily change your role

**Pull request merged**
