### PR TITLE
oni gentx and validator.md

### PR DESCRIPTION
**Pull request by kw1knode**

### CODE REVIEW

**Comment by VT-Cosmos** [comment]
@kw1knode - Thank you for the submission.

**Comment by giunatale** [comment]
Thank you for your submission. Unfortunately your application did not comply with all requirements, including those listed in the submission process at https://github.com/atomone-hub/validator/blob/main/README.md#validators in order to be considered for a Genesis validator slot. However, you may still be able to create a GovGen validator permissionlessly once GovGen chain launches.

**Comment by kw1knode** [comment]
What are we missing ? We can easily fix anything needed. Only received a thank you as in submission was good.

**Comment by kw1knode** [comment]
> What are we missing ? We can easily fix anything needed. Only received a thank you as in submission was good.

the .md is the exact same as merged applications and we did include gentx.

**Pull request closed without merging**
