### PR TITLE
add Simurgh validator

### PR DESCRIPTION
**Pull request by stevenoruzi**
add Simurgh validator

### CODE REVIEW

**Comment by VT-Cosmos** [comment]
Thank you @stevenoruzi. The community will get back to you shortly.

**Comment by VT-Cosmos** [comment]
@stevenoruzi Thank you for your submission.
There were some updated point that are missing from the application. 
* Unique validator key to submit (from Cosmos Hub)
* Region you and/or your validator is based (country)

We suggest to check the updated requirements to ensure all is covered in the submission, before the deadline.

**Comment by stevenoruzi** [comment]
@VT-Cosmos I just rebased my branch and added the region.
FYI, I'm not a validator on the Cosmos hub

**Comment by stevenoruzi** [comment]
@VT-Cosmos  I'm going to close this PR.
I submitted the PR to become a validator at a time when there were insufficient PRs(potential validators), aiming to support the continuity of the chain. Now, there are ample validators willing to participate, and I think they possess superior infrastructure and team capabilities.

**Pull request closed without merging**
