### PR TITLE
ugaenn.io request

### PR DESCRIPTION
**Pull request by gawaeuhu**
Created validator directory for ugaenn.io

### CODE REVIEW

**Comment by VT-Cosmos** [comment]
@gawaeuhu - Thank you for submitting the validator directory. 
Please remember to submit the details for the GenTX.
Also please note that the submission deadline is Feb 23, 5pm PST / Feb 24, 1am UTC

**Comment by gawaeuhu** [comment]
Added govgen-1/gentx/gentx-7b6b5e6bd22012b57c766d7aa29e62a7cdfa1ffd.json 
Thx!

**Comment by VT-Cosmos** [comment]
@gawaeuhu - The country/region is missing from the Directory. We need this information in order to consider the application

**Comment by gawaeuhu** [comment]
Our company is based in Singapore.  Added to the Directory.  Thx!

**Comment by VT-Cosmos** [comment]
@gawaeuhu 

We are moving the validator communication to a private group in the GovGen/AtomOne Discord. Which you can find here: https://discord.gg/atomone
Please join using the handle provided in your validator PR, or edit your user profile so that it designates your validator so that we can easily change your role

**Pull request merged**
