### PR TITLE
Create EquinoxDAO.md

### PR DESCRIPTION
**Pull request by samwang3**
validators directory: Add  EquinoxDAO

### CODE REVIEW

**Comment by VT-Cosmos** [comment]
Thank you for your submission @samwang3 - The community will get back to you shortly.

**Comment by samwang3** [comment]
> Thank you for your submission @samwang3 - The community will get back to you shortly.
Dear vt
 long time no see hope you are well, thank you for your work,

**Comment by VT-Cosmos** [comment]
@samwang3 

There were some updated point that are missing from the application.

Unique validator key to submit (from Cosmos Hub)
Region you and/or your validator is based (country)
We suggest that you check the updated requirements in the README to ensure all is covered in the submission, before the deadline.

Also please note that the GenTX submission deadline is Feb 23, 5pm PST / Feb 24, 1am UTC

**Comment by samwang3** [comment]
> @samwang3
> 
> There were some updated point that are missing from the application.
> 
> Unique validator key to submit (from Cosmos Hub) Region you and/or your validator is based (country) We suggest that you check the updated requirements in the README to ensure all is covered in the submission, before the deadline.
> 
> Also please note that the GenTX submission deadline is Feb 23, 5pm PST / Feb 24, 1am UTC

I will modify it 
thank you very much

**Comment by giunatale** [comment]
closing since we already have an https://github.com/atomone-hub/validator/blob/main/validator-applications/EquinoxDAO.md file coming from #31

**Pull request closed without merging**
